ALTER TABLE users ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE organ ALTER COLUMN organ_id DROP DEFAULT;
ALTER TABLE software ALTER COLUMN software_id DROP DEFAULT;
ALTER TABLE provider ALTER COLUMN provider_id DROP DEFAULT;
ALTER TABLE license ALTER COLUMN license_id DROP DEFAULT;
